#
# configure.ac
# This file is part of dir-index.sh.
#
# Copyright (C) 2026  The dir-index.sh authors
# <https://github.com/jefferyto/dir-index.sh>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <https://www.gnu.org/licenses/>.
#

# Process this file with autoconf to produce a configure script.

AC_PREREQ([2.69])
AC_INIT(
	[dir-index.sh],
	[1.0.0-dev],
	[https://github.com/jefferyto/dir-index.sh/issues],
	[dir-index-sh],
	[https://github.com/jefferyto/dir-index.sh]
)
AC_CONFIG_AUX_DIR([build-aux])
AM_INIT_AUTOMAKE([foreign])

AC_COPYRIGHT([Copyright (C) 2026  The dir-index.sh authors])

# Checks for programs.

# Checks for libraries.

# Checks for header files.

# Checks for typedefs, structures, and compiler characteristics.

# Checks for library functions.

AC_CONFIG_FILES([
	Makefile
	src/usr/bin/Makefile
	src/usr/share/dir-index-sh/styles/Makefile
])

AC_REQUIRE_AUX_FILE([tap-driver.sh])

AC_OUTPUT
